In [18]:
import numpy as np

def naive_gaussian_elimination_partial_pivoting_verbose(A, b):
   

    n = len(b)
    
    # Convert inputs to numpy arrays
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    
    # Augmented matrix
    Ab = np.hstack((A, b.reshape(-1, 1)))

    print("Initial augmented matrix:")
    print(np.round(Ab, 3))

    for i in range(n):
        # Partial pivoting
        pivot_row = np.argmax(np.abs(Ab[i:, i])) + i
        Ab[[i, pivot_row]] = Ab[[pivot_row, i]]

        print(f"\nStep {i+1}: Partial Pivoting")
        print("Pivoted augmented matrix:")
        print(np.round(Ab, 3))

        # Gaussian elimination
        for j in range(i + 1, n):
            factor = Ab[j, i] / Ab[i, i]
            Ab[j, i:] -= factor * Ab[i, i:]

        print(f"\nStep {i+1}: Gaussian Elimination")
        print("Gaussian eliminated augmented matrix:")
        print(np.round(Ab, 3))

    # Back substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (Ab[i, -1] - np.dot(Ab[i, i+1:n], x[i+1:])) / Ab[i, i]

    return np.round(x, 3)

# Example usage
A = [[25, 5, 1], 
     [64, 8, 1], 
     [144, 12, 1]]
b = [106.8, 177.2, 279.2]

solution = naive_gaussian_elimination_partial_pivoting_verbose(A, b)
print("\nSolution:", solution)


Initial augmented matrix:
[[ 25.    5.    1.  106.8]
 [ 64.    8.    1.  177.2]
 [144.   12.    1.  279.2]]

Step 1: Partial Pivoting
Pivoted augmented matrix:
[[144.   12.    1.  279.2]
 [ 64.    8.    1.  177.2]
 [ 25.    5.    1.  106.8]]

Step 1: Gaussian Elimination
Gaussian eliminated augmented matrix:
[[144.     12.      1.    279.2  ]
 [  0.      2.667   0.556  53.111]
 [  0.      2.917   0.826  58.328]]

Step 2: Partial Pivoting
Pivoted augmented matrix:
[[144.     12.      1.    279.2  ]
 [  0.      2.917   0.826  58.328]
 [  0.      2.667   0.556  53.111]]

Step 2: Gaussian Elimination
Gaussian eliminated augmented matrix:
[[ 1.4400e+02  1.2000e+01  1.0000e+00  2.7920e+02]
 [ 0.0000e+00  2.9170e+00  8.2600e-01  5.8328e+01]
 [ 0.0000e+00  0.0000e+00 -2.0000e-01 -2.1700e-01]]

Step 3: Partial Pivoting
Pivoted augmented matrix:
[[ 1.4400e+02  1.2000e+01  1.0000e+00  2.7920e+02]
 [ 0.0000e+00  2.9170e+00  8.2600e-01  5.8328e+01]
 [ 0.0000e+00  0.0000e+00 -2.0000e-01 -2.1700e-01]